language: java
jdk:
 - oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ls && pwd
deploy:
  provider: releases
  api_key:
    secure: YOUR_API_KEY_ENCRYPTED
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
